- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy the config. file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


- name: Downloading and Extracting the app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: enable and start the systemd service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true

