- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    status: installed




func_app_prereq

cd /app

func_print_head "Download the dependencies"
go mod init dispatch &>>$log_file
func_stat_check $?
go get &>>$log_file
func_stat_check $?
go build &>>$log_file
func_stat_check $?

func_systemd_setup
