- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Import app prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: downloading the dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: Import SystemD setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup

- name: Import Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter.yml