- name: Import Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Start Prometheus
  ansible.builtin.systemd:
    state: restarted
    name: prometheus
    enabled: true