- name: Import Prometheus Configuration
  ansible.builtin.template:
    src: "{{ item }}.yml"
    dest: /opt/prometheus/{{item}}.yml
    loop:
      - prometheus
      - alerts

- name: Start Prometheus
  ansible.builtin.systemd:
    state: restarted
    name: prometheus
    enabled: true

- name: checking if the prometheus is working or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15

# delay : 10 don't start checking for 10 sec
# one more wat to check the status of the port
# we can write the above using shell as below
# ansible.builtin.shell: sleep 10 ; netstat -lntp | grep 9090