- name: Coping Catalogue Service files
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: enable and start the {{component}} service
  ansible.builtin.systemd:
    state: restarted
    name: "{{component}}"
    enabled: true
    daemon_reload: true

