groups:
  - name: HighCPUUtilization
    rules:
      - alert: HighCPUUtilization
        expr: 100 - (avg by(component,env,job,name) (rate(node_cpu_seconds_total{mode="idle"}[5m]))*100) > 20
        for: 1m
        labels:
          severity: page
        annotations:
          summary: High CPU usage